Repository vaadin/vaadin-combo-box-flow, pull requests merged in 2019-02, with the labels that each got.

#202 Disable client side validation on setRequiredIndicatorVisible
  vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/RequiredComboboxPage.java
  vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/AbstractComboBoxIT.java
  vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/RequiredComboboxIT.java
  vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
  vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
Labels: in progress

#204 Add maven profile to use bower in integration tests
  .gitignore
  vaadin-combo-box-flow-integration-tests/build-tools/package.json
  vaadin-combo-box-flow-integration-tests/pom.xml
  vaadin-combo-box-flow-integration-tests/src/main/webapp/frontend/bower.json
Labels: in review

#209 Update only one item on DataProvider::refreshItem
  vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/bean/SimpleBean.java
  vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/RefreshDataProviderPage.java
  vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/RefreshDataProviderIT.java
  vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
Labels: in progress

#206 Add IT for resolving loading state when 0 items returned
  vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/LazyLoadingPage.java
  vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java
Labels: in progress

#205 Add IT for decreasing the data set size
  vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/DataProviderPage.java
  vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/DataProviderIT.java
Labels: in progress

#210 Bump flow version to 1.4-SNAPSHOT
  pom.xml
Labels: in review unscoped

#218 Update Base version to 1.3-snapshot
  pom.xml
Labels: in review unscoped
